image: gitlab/dind

services:
  - name: docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  WIZ_POLICY: "nixlab-vuln"

stages:
  - image-build-scan-push-tag

image-build-scan-push-tag:
  allow_failure: true
  stage: image-build-scan-push-tag
  before_script:
    - curl --silent -o wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64 && chmod +x wizcli
    - ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
  script:
    - docker build . --tag $CONTAINER_RELEASE_IMAGE
    - ./wizcli docker scan --image $CONTAINER_RELEASE_IMAGE --policy "$WIZ_POLICY" --output wiz-output.json,sarif,true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
    - ./wizcli docker tag -S -i $CONTAINER_RELEASE_IMAGE
  artifacts:
    paths:
      - wiz-output.json
